name: 'Nudgeer Action'
description: 'Get your security insights on each deployment'
author: 'Mahmoud@Onboardbase'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'shield'
  color: 'green'

# Define your inputs here.
inputs:
  domain:
    description: 'Your domain, deployment domain'
    required: true
  wait:
    description: 'Used to wait till the deployment is live'
    default: '3000' # 3sec default
  github_token:
    description: 'Used to comment on the PR, GH token for the repo with write access'
    default: ${{ github.token }}
    required: false

# Define your outputs here.
outputs:
  score:
    description: 'Nudgeer score'
  report:
    description: 'Nudgeer secrets report details'

runs:
  using: node20
  main: dist/index.js
